- hosts: all
#    become: true
  tasks:
  - name: create a docker image with deployed war file
    command: docker build -t rladbsals23/cicd-project-ansible
    args:
        chdir: /root
  
  - name: push the image on Docker Hub
    command: docker push rladbsals23/cicd-project-ansible

  - name: remove the docker image from the ansible server
    command: docker rmi rladbsals23/cicd-project-ansible
    ignore_errors: yes